services:
  professional-task-manager-api:
    image: node:16
    container_name: task-manager-api
    working_dir: /app
    command: sh -c 'npm install && cd ./src && npx sequelize db:migrate && cd .. && npm run dev'
    ports:
      - 8888:3000
    volumes:
      - ./:/app
    environment:
      NODE_ENV: "development"
      DATABASE_HOST: 172.17.0.1
      DATABASE_PORT: 3307
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: AjboyIan_321
      DATABASE_NAME: ptm
      DATABASE_DIALECT: "mysql"
