services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ptm-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: AjboyIan_321
      MYSQL_DATABASE: ptm
  professional-task-manager-api:
    image: node:16
    container_name: task-manager-api
    working_dir: /app
    command: sh -c 'npm install && cd ./src && npx sequelize db:migrate && cd .. && npm run dev'
    ports:
      - 8888:3000
    volumes:
      - ./:/app
    environment:
      NODE_ENV: "development"
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: AjboyIan_321
      DATABASE_NAME: ptm
      DATABASE_DIALECT: "mysql"
    depends_on:
      - mysql

volumes:
  ptm-mysql-data:
